minimum_pre_commit_version: 2.15.0
exclude: ^LICENSES/|\.(html|csv|svg)|docs/$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: local
    # note: assumes python env is setup and activated
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        require_serial: true
        types_or: [python, pyi]
        verbose: true
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types_or: [python, pyi]
        args: [--load-plugins=pylint.extensions.redefined_loop_name]
        exclude: docs/
    -   id: pylint-unspecified-encoding
        entry: pylint
        name: Using open without explicitly specifying an encoding
        alias: unspecified-encoding
        language: system
        types_or: [python, pyi]
        args: [--disable=all, --enable=unspecified-encoding]
        exclude: docs/
    -   id: pytest
        name: pytest
        entry: pytest --cov=atmospheric_explorer --log-disable=true tests/
        language: system
        always_run: true
        pass_filenames: false
        types_or: [python, pyi]
        verbose: true
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.264
    hooks:
    -   id: ruff
        args: [--exit-non-zero-on-fix]
        exclude: docs/
-   repo: https://github.com/pycqa/pydocstyle
    rev: 07f6707e2c5612960347f7c00125620457f490a7
    hooks:
    -   id: pydocstyle
        files: atmospheric_explorer/
