carbon_dioxide:
  mean_column:
    surface:
      instantaneous:
        conversion_factor: [28.97 / 44.01 * 1e6]
        original_units: [mol mol-1]
        convert_units: [ppmv]
        cams_variables: [XCO2]
        long_names: [CO2 total column dry mole fraction]
    satellite:
      instantaneous:
        conversion_factor: [28.97 / 44.01 * 1e6]
        original_units: [mol mol-1]
        convert_units: [ppmv]
        cams_variables: [XCO2]
        long_names: [CO2 total column dry mole fraction]
  surface_flux:
    surface:
      instantaneous:
        conversion_factor: [1,1,1,1,1]
        original_units: [(0-1),m2,kgC m-2 s-1,kgC m-2 s-1,kgC m-2 s-1]
        convert_units: [(0-1),m2,kgC m-2 s-1,kgC m-2 s-1,kgC m-2 s-1]
        cams_variables: [lsf,area,flux_apri,flux_apos,flux_foss]
        long_names: [Land-sea fraction,Grid box area,Prior surface upward mass flux of carbon
          (including fossile),Posterior surface upward mass flux of carbon (including fossile),Fossile
          emissions of carbon for the whole grid box]
      monthly_mean:
        conversion_factor: [1,1,1,1,1,1,1]
        original_units: [kgC m-2 month-1,kgC m-2 month-1,kgC m-2 month-1,kgC m-2 month-1,kgC
          m-2 month-1,(0-1),m2]
        convert_units: [kgC m-2 month-1,kgC m-2 month-1,kgC m-2 month-1,kgC m-2 month-1,kgC
          m-2 month-1,(0-1),m2]
        cams_variables: [flux_apri_bio,flux_apri_ocean,flux_apos_bio,flux_apos_ocean,flux_foss,lsf,area]
        long_names: [Prior land surface upward mass flux of carbon for the whole grid box
          and the whole month without fossile,Prior ocean surface upward mass flux of carbon
          for the whole grid box and the whole month without fossile,Posterior land surface
          upward mass flux of carbon for the whole grid box and the whole month without
          fossile,Posterior ocean surface upward mass flux of carbon for the whole grid
          box and the whole month without fossile,Fossile emissions of carbon for the whole
          grid box and the whole month,Land-sea fraction,Grid box area]
    satellite:
      instantaneous:
        conversion_factor: [1,1,1,1,1]
        original_units: [(0-1),m2,kgC m-2 s-1,kgC m-2 s-1,kgC m-2 s-1]
        convert_units: [(0-1),m2,kgC m-2 s-1,kgC m-2 s-1,kgC m-2 s-1]
        cams_variables: [lsf,area,flux_apri,flux_apos,flux_foss]
        long_names: [Land-sea fraction,Grid box area,Prior surface upward mass flux of carbon
          (including fossile),Posterior surface upward mass flux of carbon (including fossile),Fossile
          emissions of carbon for the whole grid box]
      monthly_mean:
        conversion_factor: [1,1,1,1,1,1,1]
        original_units: [kgC m-2 month-1,kgC m-2 month-1,kgC m-2 month-1,kgC m-2 month-1,kgC
          m-2 month-1,(0-1),m2]
        convert_units: [kgC m-2 month-1,kgC m-2 month-1,kgC m-2 month-1,kgC m-2 month-1,kgC
          m-2 month-1,(0-1),m2]
        cams_variables: [flux_apri_bio,flux_apri_ocean,flux_apos_bio,flux_apos_ocean,flux_foss,lsf,area]
        long_names: [Prior land surface upward mass flux of carbon for the whole grid box
          and the whole month without fossile,Prior ocean surface upward mass flux of carbon
          for the whole grid box and the whole month without fossile,Posterior land surface
          upward mass flux of carbon for the whole grid box and the whole month without
          fossile,Posterior ocean surface upward mass flux of carbon for the whole grid
          box and the whole month without fossile,Fossile emissions of carbon for the whole
          grid box and the whole month,Land-sea fraction,Grid box area]
  concentration:
    surface:
      instantaneous:
        conversion_factor: [1,1,1,1,1]
        original_units: [mol mol-1,m,Pa,Pa,1]
        convert_units: [mol mol-1,m,Pa,Pa,1]
        cams_variables: [CO2,height_above_reference_ellipsoid,Psurf,ap,bp]
        long_names: [CO2 dry mole fraction,Altitude of layer interfaces above the reference
          ellipsoid,Surface pressure,Ai coeff in Pi = Ai + Bi.Psurf,Bi coeff in Pi = Ai
          + Bi.Psurf]
    satellite:
      instantaneous:
        conversion_factor: [1,1,1,1,1]
        original_units: [mol mol-1,m,Pa,Pa,1]
        convert_units: [mol mol-1,m,Pa,Pa,1]
        cams_variables: [CO2,height_above_reference_ellipsoid,Psurf,ap,bp]
        long_names: [CO2 dry mole fraction,Altitude of layer interfaces above the reference
          ellipsoid,Surface pressure,Ai coeff in Pi = Ai + Bi.Psurf,Bi coeff in Pi = Ai
          + Bi.Psurf]
nitrous_oxide:
  surface_flux:
    surface:
      monthly_mean:
        conversion_factor: [1]
        original_units: [kgN m-2 month-1]
        convert_units: [kgN m-2 month-1]
        cams_variables: [N2O]
        long_names: [Surface upward mass flux of nitrogen for the whole grid box and the
          whole month]
  concentration:
    surface:
      instantaneous:
        conversion_factor: [28.97 / 46.1 * 1e9,1,1,1]
        original_units: [1e-9 mol mol-1,Pa,Pa,1]
        convert_units: [ppbv,Pa,Pa,1]
        cams_variables: [N2O,Psurf,ap,bp]
        long_names: [N2O dry mole fraction,Surface pressure,Ai coeff in Pi = Ai + Bi.Psurf,Bi
          coeff in Pi = Ai + Bi.Psurfs]
methane:
  mean_column:
    first_guess:
      instantaneous:
        conversion_factor: [1,1,1,1,28.97 / 16.044 * 1e9]
        original_units: [degrees_east,degrees_north,m2,Pa,1e-9]
        convert_units: [degrees_east,degrees_north,m2,Pa,ppbv]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,ps,CH4]
        long_names: [Longitude bounds,Latitude bounds,Cell area,Ps,Ch4]
    surface:
      instantaneous:
        conversion_factor: [1,1,1,1,28.97 / 16.044 * 1e9]
        original_units: [degrees_east,degrees_north,m2,Pa,1e-9]
        convert_units: [degrees_east,degrees_north,m2,Pa,ppbv]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,ps,CH4]
        long_names: [Longitude bounds,Latitude bounds,Cell area,Ps,Ch4]
    surface_satellite:
      instantaneous:
        conversion_factor: [1,1,1,1,28.97 / 16.044 * 1e9]
        original_units: [degrees_east,degrees_north,m2,Pa,1e-9]
        convert_units: [degrees_east,degrees_north,m2,Pa,ppbv]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,ps,CH4]
        long_names: [Longitude bounds,Latitude bounds,Cell area,Ps,Ch4]
  surface_flux:
    first_guess:
      monthly_mean:
        conversion_factor: [1,1,1,1,1,1,1,1,1]
        original_units: [degrees_east,degrees_north,m2,null,kg m-2 s-1,kg m-2 s-1,kg m-2 s-1,kg
          m-2 s-1,kg m-2 s-1]
        convert_units: [degrees_east,degrees_north,m2,null,kg m-2 s-1,kg m-2 s-1,kg m-2 s-1,kg
          m-2 s-1,kg m-2 s-1]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,time_bounds,ch4_emis_wetlands,ch4_emis_rice,ch4_emis_biomass_burning,ch4_emis_other,ch4_emis_total]
        long_names: [Longitude bounds,Latitude bounds,Cell area,Time bounds,surface upward
          mass flux of methane from wetlands sources,surface upward mass flux of methane
          from rice sources,surface upward mass flux of methane from biomass-burning sources,surface
          upward mass flux of methane from other sources,surface upward mass flux of methane]
    surface:
      monthly_mean:
        conversion_factor: [1,1,1,1,1,1,1,1,1]
        original_units: [degrees_east,degrees_north,m2,null,kg m-2 s-1,kg m-2 s-1,kg m-2 s-1,kg
          m-2 s-1,kg m-2 s-1]
        convert_units: [degrees_east,degrees_north,m2,null,kg m-2 s-1,kg m-2 s-1,kg m-2 s-1,kg
          m-2 s-1,kg m-2 s-1]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,time_bounds,ch4_emis_wetlands,ch4_emis_rice,ch4_emis_biomass_burning,ch4_emis_other,ch4_emis_total]
        long_names: [Longitude bounds,Latitude bounds,Cell area,Time bounds,surface upward
          mass flux of methane from wetlands sources,surface upward mass flux of methane
          from rice sources,surface upward mass flux of methane from biomass-burning sources,surface
          upward mass flux of methane from other sources,surface upward mass flux of methane]
    surface_satellite:
      monthly_mean:
        conversion_factor: [1,1,1,1,1,1,1,1,1]
        original_units: [degrees_east,degrees_north,m2,null,kg m-2 s-1,kg m-2 s-1,kg m-2 s-1,kg
          m-2 s-1,kg m-2 s-1]
        convert_units: [degrees_east,degrees_north,m2,null,kg m-2 s-1,kg m-2 s-1,kg m-2 s-1,kg
          m-2 s-1,kg m-2 s-1]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,time_bounds,ch4_emis_wetlands,ch4_emis_rice,ch4_emis_biomass_burning,ch4_emis_other,ch4_emis_total]
        long_names: [Longitude bounds,Latitude bounds,Cell area,Time bounds,surface upward
          mass flux of methane from wetlands sources,surface upward mass flux of methane
          from rice sources,surface upward mass flux of methane from biomass-burning sources,surface
          upward mass flux of methane from other sources,surface upward mass flux of methane]
  concentration:
    first_guess:
      instantaneous:
        conversion_factor: [1,1,1,1,1,1,1,1,28.97 / 16.044 * 1e9,1,1,1]
        original_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,1e-9,K,1,m]
        convert_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,ppbv,K,1,m]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,hyam,hybm,hyai,hybi,ps,CH4,T,Q,altitude]
        long_names: [Longitude bounds,Latitude bounds,Cell area,hybrid A coefficient at layer
          layer mid,hybrid B coefficient at layer layer mid,hybrid A coefficient at layer
          layer interface,hybrid B coefficient at layer layer interface,Ps,mole fraction
          of methane in (humid) air,T,Q,Altitude]
      daily_mean:
        conversion_factor: [1,1,1,1,1,1,1,1,28.97 / 16.044 * 1e9,1,1,1]
        original_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,1e-9,K,1,m]
        convert_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,ppbv,K,1,m]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,hyam,hybm,hyai,hybi,ps,CH4,T,Q,altitude]
        long_names: [Longitude bounds,Latitude bounds,Cell area,hybrid A coefficient at layer
          layer mid,hybrid B coefficient at layer layer mid,hybrid A coefficient at layer
          layer interface,hybrid B coefficient at layer layer interface,Ps,mole fraction
          of methane in (humid) air,T,Q,Altitude]
    surface:
      instantaneous:
        conversion_factor: [1,1,1,1,1,1,1,1,28.97 / 16.044 * 1e9,1,1,1]
        original_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,1e-9,K,1,m]
        convert_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,ppbv,K,1,m]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,hyam,hybm,hyai,hybi,ps,CH4,T,Q,altitude]
        long_names: [Longitude bounds,Latitude bounds,Cell area,hybrid A coefficient at layer
          layer mid,hybrid B coefficient at layer layer mid,hybrid A coefficient at layer
          layer interface,hybrid B coefficient at layer layer interface,Ps,mole fraction
          of methane in (humid) air,T,Q,Altitude]
      daily_mean:
        conversion_factor: [1,1,1,1,1,1,1,1,28.97 / 16.044 * 1e9,1,1,1]
        original_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,1e-9,K,1,m]
        convert_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,ppbv,K,1,m]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,hyam,hybm,hyai,hybi,ps,CH4,T,Q,altitude]
        long_names: [Longitude bounds,Latitude bounds,Cell area,hybrid A coefficient at layer
          layer mid,hybrid B coefficient at layer layer mid,hybrid A coefficient at layer
          layer interface,hybrid B coefficient at layer layer interface,Ps,mole fraction
          of methane in (humid) air,T,Q,Altitude]
    surface_satellite:
      instantaneous:
        conversion_factor: [1,1,1,1,1,1,1,1,28.97 / 16.044 * 1e9,1,1,1]
        original_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,1e-9,K,1,m]
        convert_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,ppbv,K,1,m]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,hyam,hybm,hyai,hybi,ps,CH4,T,Q,altitude]
        long_names: [Longitude bounds,Latitude bounds,Cell area,hybrid A coefficient at layer
          layer mid,hybrid B coefficient at layer layer mid,hybrid A coefficient at layer
          layer interface,hybrid B coefficient at layer layer interface,Ps,mole fraction
          of methane in (humid) air,T,Q,Altitude]
      daily_mean:
        conversion_factor: [1,1,1,1,1,1,1,1,28.97 / 16.044 * 1e9,1,1,1]
        original_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,1e-9,K,1,m]
        convert_units: [degrees_east,degrees_north,m2,Pa,1,Pa,1,Pa,ppbv,K,1,m]
        cams_variables: [longitude_bounds,latitude_bounds,cell_area,hyam,hybm,hyai,hybi,ps,CH4,T,Q,altitude]
        long_names: [Longitude bounds,Latitude bounds,Cell area,hybrid A coefficient at layer
          layer mid,hybrid B coefficient at layer layer mid,hybrid A coefficient at layer
          layer interface,hybrid B coefficient at layer layer interface,Ps,mole fraction
          of methane in (humid) air,T,Q,Altitude]
